version: '3.8'

# Docker Compose override for development
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development overrides for Ultra API
  ultra-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Stop at builder stage for development
    volumes:
      - .:/app:cached
      - go_modules_cache:/go/pkg/mod  # Cache Go modules
    environment:
      - GO_ENV=development
      - DEBUG=true
      - LOG_LEVEL=debug
    command: go run -race main.go  # Run with race detector in dev
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"  # Explicit port mapping for clarity

  # Development overrides for PostgreSQL
  postgres:
    environment:
      - POSTGRES_LOG_STATEMENT=all  # Log all SQL statements
      - POSTGRES_LOG_MIN_MESSAGES=info
      - POSTGRES_LOG_DURATION=on
    ports:
      - "5432:5432"  # Expose for local development tools
    command: postgres -c log_statement=all -c log_connections=on -c log_disconnections=on

  # Development overrides for MongoDB
  mongo:
    ports:
      - "27017:27017"  # Expose for local development tools
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend --verbose

  # Development services
  mailcatcher:
    image: schickling/mailcatcher
    container_name: ultra_mailcatcher
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP
    networks:
      - ultra-network

  # Redis for caching/sessions in development
  redis:
    image: redis:7-alpine
    container_name: ultra_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ultra-network
    command: redis-server --appendonly yes

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ultra_redis_commander
    ports:
      - "8083:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - ultra-network
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
  go_modules_cache:
    driver: local