-- Generated from data/food.csv
-- Total foods: 526
-- Generated at: 2026-01-31 15:25:26

INSERT INTO general_foods (name, description, calories, protein, carbs, fat, fiber, tag, created_at, updated_at)
VALUES
  ('Dessert', '', 255, 4, 33, 11, 0, 'general', NOW(), NOW()),
  ('Avocat cru', '', 203, 2, 0, 21, 0, 'general', NOW(), NOW()),
  ('Chayote', '', 19, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Graine germée de luzerne', '', 29, 4, 1, 1, 0, 'general', NOW(), NOW()),
  ('Bette', '', 13, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Carotte', '', 30, 1, 5, 0, 0, 'general', NOW(), NOW()),
  ('Champignon cru', '', 24, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Salade', '', 26, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Chou rouge cru', '', 26, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Chou-fleur cru', '', 25, 2, 2, 1, 0, 'general', NOW(), NOW()),
  ('Concombre cru', '', 17, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Courgette', '', 17, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Cresson de fontaine cru', '', 16, 2, 1, 0, 0, 'general', NOW(), NOW()),
  ('Céleri branche cru', '', 15, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Endive', '', 17, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Fenouil cru', '', 18, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Laitue', '', 15, 1, 1, 0, 0, 'general', NOW(), NOW()),
  ('Oignon cru', '', 39, 1, 6, 1, 0, 'general', NOW(), NOW()),
  ('Pissenlit cru', '', 49, 3, 6, 1, 0, 'general', NOW(), NOW()),
  ('Poireau cru', '', 30, 2, 5, 0, 0, 'general', NOW(), NOW()),
  ('Poivron vert jaune cru', '', 23, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Potiron cru', '', 20, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Radis rouge cru', '', 11, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Artichaut cru', '', 45, 3, 5, 0, 0, 'general', NOW(), NOW()),
  ('Aubergine', '', 23, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Cardon cru', '', 14, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Céleri-rave cru', '', 26, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Champignon de Paris cru', '', 21, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Brocoli cru', '', 32, 3, 2, 0, 0, 'general', NOW(), NOW()),
  ('Chou de Bruxelles cru', '', 44, 3, 5, 0, 0, 'general', NOW(), NOW()),
  ('Épinard cru', '', 33, 3, 3, 0, 0, 'general', NOW(), NOW()),
  ('Haricot vert cru', '', 32, 2, 4, 0, 0, 'general', NOW(), NOW()),
  ('Navet cru', '', 26, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Chou-rave cru', '', 25, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Chou vert cru', '', 24, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Petits pois', '', 81, 5, 11, 0, 0, 'general', NOW(), NOW()),
  ('Epinard cru', '', 28, 3, 1, 1, 0, 'general', NOW(), NOW()),
  ('Petits pois surgelés', '', 78, 6, 10, 0, 0, 'general', NOW(), NOW()),
  ('Poivron vert cru', '', 23, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Poivron rouge cru', '', 34, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Radis noir cru', '', 28, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Scarole', '', 21, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Betterave rouge', '', 40, 2, 6, 0, 0, 'general', NOW(), NOW()),
  ('Échalote', '', 62, 2, 12, 0, 0, 'general', NOW(), NOW()),
  ('Mâche', '', 15, 2, 1, 0, 0, 'general', NOW(), NOW()),
  ('Légumes', '', 65, 2, 6, 3, 0, 'general', NOW(), NOW()),
  ('Champignon', '', 25, 1, 2, 1, 0, 'general', NOW(), NOW()),
  ('Maïs doux cru', '', 97, 3, 17, 1, 0, 'general', NOW(), NOW()),
  ('Oseille', '', 23, 2, 2, 1, 0, 'general', NOW(), NOW()),
  ('Chou blanc cru', '', 35, 1, 5, 1, 0, 'general', NOW(), NOW()),
  ('Tomate verte', '', 25, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Batavia', '', 15, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Pourpier cru', '', 0, 2, 0, 0, 0, 'general', NOW(), NOW()),
  ('Courge musquée', '', 24, 1, 5, 0, 0, 'general', NOW(), NOW()),
  ('Potimarron cru', '', 22, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Courge hokkaïdo', '', 56, 1, 10, 1, 0, 'general', NOW(), NOW()),
  ('Courge melonnette', '', 31, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Courge butternut (doubeurre)', '', 31, 1, 5, 0, 0, 'general', NOW(), NOW()),
  ('Courge', '', 14, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Courge spaghetti', '', 32, 1, 5, 1, 0, 'general', NOW(), NOW()),
  ('Piment cru', '', 37, 2, 6, 0, 0, 'general', NOW(), NOW()),
  ('Chicorée rouge', '', 19, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Chicorée verte', '', 16, 2, 1, 1, 0, 'general', NOW(), NOW()),
  ('Citrouille', '', 30, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Chou chinois pé-tsaï cru', '', 16, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Poivron jaune cru', '', 29, 1, 5, 0, 0, 'general', NOW(), NOW()),
  ('Laitue romaine', '', 17, 1, 1, 0, 0, 'general', NOW(), NOW()),
  ('Tomate cerise', '', 32, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Pois mange-tout cru', '', 43, 3, 6, 0, 0, 'general', NOW(), NOW()),
  ('Panais cru', '', 68, 1, 13, 0, 0, 'general', NOW(), NOW()),
  ('Graine germée de haricot mungo', '', 28, 3, 3, 0, 0, 'general', NOW(), NOW()),
  ('Tomate côtelée', '', 17, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Haricot beurre cru', '', 38, 2, 6, 0, 0, 'general', NOW(), NOW()),
  ('Salsifis noir cru', '', 83, 3, 15, 0, 0, 'general', NOW(), NOW()),
  ('Bambou', '', 29, 3, 3, 0, 0, 'general', NOW(), NOW()),
  ('Cresson alénois cru', '', 24, 3, 1, 1, 0, 'general', NOW(), NOW()),
  ('Laitue iceberg', '', 17, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Rutabaga cru', '', 33, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Carotte surgelée', '', 34, 1, 5, 0, 0, 'general', NOW(), NOW()),
  ('Petits pois et carottes surgelés', '', 53, 3, 7, 0, 0, 'general', NOW(), NOW()),
  ('Roquette', '', 28, 3, 2, 1, 0, 'general', NOW(), NOW()),
  ('Chou frisé cru', '', 50, 4, 4, 1, 0, 'general', NOW(), NOW()),
  ('Courgette surgelée', '', 17, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Crosne cru', '', 52, 7, 6, 0, 0, 'general', NOW(), NOW()),
  ('Salsifis cru', '', 41, 2, 5, 0, 0, 'general', NOW(), NOW()),
  ('Oignon rouge cru', '', 35, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Oignon jaune cru', '', 36, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Légumes pour potages surgelés', '', 34, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Julienne surgelée', '', 28, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Légumes pour ratatouille surgelés', '', 21, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Printanière surgelée', '', 51, 2, 8, 0, 0, 'general', NOW(), NOW()),
  ('Haricot plat cru', '', 32, 2, 4, 0, 0, 'general', NOW(), NOW()),
  ('Mesclun', '', 22, 2, 3, 0, 0, 'general', NOW(), NOW()),
  ('Tomate ronde', '', 18, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Asperge', '', 25, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Chou romanesco cru', '', 30, 3, 2, 0, 0, 'general', NOW(), NOW()),
  ('Salicorne (Salicornia sp.)', '', 13, 1, 1, 0, 0, 'general', NOW(), NOW()),
  ('Salade sucrine', '', 17, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Salade feuille de chêne', '', 11, 1, 1, 0, 0, 'general', NOW(), NOW()),
  ('Chou chinois pak choï cru', '', 15, 2, 1, 0, 0, 'general', NOW(), NOW()),
  ('Tomate marmande', '', 0, 0, 3, 0, 0, 'general', NOW(), NOW()),
  ('Tomate noire de Crimée', '', 0, 0, 3, 0, 0, 'general', NOW(), NOW()),
  ('Tomate allongée', '', 19, 0, 3, 0, 0, 'general', NOW(), NOW()),
  ('Chou kale cru', '', 35, 3, 0, 1, 0, 'general', NOW(), NOW()),
  ('Moringa cru', '', 0, 2, 5, 0, 0, 'general', NOW(), NOW()),
  ('Tomate sans précision', '', 19, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Légumes pour couscous surgelés', '', 44, 2, 6, 1, 0, 'general', NOW(), NOW()),
  ('Graine germée de lentille', '', 123, 9, 19, 1, 0, 'general', NOW(), NOW()),
  ('Tomate grappe', '', 20, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Salade verte', '', 14, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Crudité', '', 28, 1, 3, 1, 0, 'general', NOW(), NOW()),
  ('Banane plantain', '', 132, 1, 30, 0, 0, 'general', NOW(), NOW()),
  ('Gombo cru', '', 31, 2, 4, 0, 0, 'general', NOW(), NOW()),
  ('Poivron vert jaune cuit', '', 33, 1, 5, 0, 0, 'general', NOW(), NOW()),
  ('Artichaut cuit', '', 33, 3, 1, 0, 0, 'general', NOW(), NOW()),
  ('Carotte appertiséee', '', 22, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Chou vert cuit', '', 24, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Chou-fleur bouilli', '', 21, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Coeur de palmier', '', 42, 3, 6, 1, 0, 'general', NOW(), NOW()),
  ('Céleri-rave cuit', '', 37, 1, 5, 1, 0, 'general', NOW(), NOW()),
  ('Épinard cuit', '', 20, 3, 0, 0, 0, 'general', NOW(), NOW()),
  ('Graine germée de haricot mungo appertiséee', '', 22, 2, 3, 0, 0, 'general', NOW(), NOW()),
  ('Haricot vert cuit', '', 29, 2, 3, 0, 0, 'general', NOW(), NOW()),
  ('Navet cuit', '', 25, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Oignon cuit', '', 35, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Petits pois appertiséss', '', 93, 5, 14, 1, 0, 'general', NOW(), NOW()),
  ('Poireau cuit', '', 0, 1, 0, 0, 0, 'general', NOW(), NOW()),
  ('Salsifis cuit', '', 68, 3, 12, 0, 0, 'general', NOW(), NOW()),
  ('Tomate appertiséee', '', 16, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Maïs doux cuit', '', 106, 3, 19, 2, 0, 'general', NOW(), NOW()),
  ('Macédoine de légumes appertiséee', '', 40, 2, 6, 0, 0, 'general', NOW(), NOW()),
  ('Épinard', '', 25, 3, 1, 1, 0, 'general', NOW(), NOW()),
  ('Haricot vert', '', 23, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Haricot beurre', '', 23, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Maïs doux', '', 105, 3, 18, 2, 0, 'general', NOW(), NOW()),
  ('Artichaut', '', 40, 2, 7, 0, 0, 'general', NOW(), NOW()),
  ('Tomate', '', 99, 4, 17, 1, 0, 'general', NOW(), NOW()),
  ('Artichaut cuit à la vapeur sous pression', '', 46, 3, 3, 0, 0, 'general', NOW(), NOW()),
  ('Asperge appertiséee', '', 20, 2, 1, 1, 0, 'general', NOW(), NOW()),
  ('Chou de Bruxelles', '', 38, 3, 4, 1, 0, 'general', NOW(), NOW()),
  ('Céleri branche', '', 13, 1, 1, 0, 0, 'general', NOW(), NOW()),
  ('Champignon de Paris', '', 18, 2, 1, 0, 0, 'general', NOW(), NOW()),
  ('Salsifis', '', 29, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Poivron vert cuit', '', 17, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Poivron rouge cuit', '', 38, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Petits pois et carottes appertiséss', '', 54, 3, 9, 0, 0, 'general', NOW(), NOW()),
  ('Chou-rave bouilli', '', 28, 2, 4, 0, 0, 'general', NOW(), NOW()),
  ('Chou rouge bouilli', '', 25, 2, 3, 0, 0, 'general', NOW(), NOW()),
  ('Potiron cuit', '', 26, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Champignon de Paris bouilli', '', 29, 2, 3, 0, 0, 'general', NOW(), NOW()),
  ('Fenouil bouilli', '', 12, 1, 1, 0, 0, 'general', NOW(), NOW()),
  ('Fondue de poireau', '', 58, 1, 0, 5, 0, 'general', NOW(), NOW()),
  ('Tomate appertisée', '', 22, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Tétragone cornue', '', 14, 1, 1, 0, 0, 'general', NOW(), NOW()),
  ('Rutabaga cuit', '', 26, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Bambou appertiséeses', '', 19, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Champignon cuit', '', 61, 2, 12, 0, 0, 'general', NOW(), NOW()),
  ('Pois mange-tout bouilli', '', 31, 2, 3, 0, 0, 'general', NOW(), NOW()),
  ('Chou frisé cuit', '', 30, 2, 4, 0, 0, 'general', NOW(), NOW()),
  ('Chou chinois pé-tsaï', '', 19, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Cardon cuit', '', 22, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Pois mange-tout', '', 47, 4, 6, 0, 0, 'general', NOW(), NOW()),
  ('Haricots verts', '', 56, 2, 4, 3, 0, 'general', NOW(), NOW()),
  ('Légumes (3-4 sortes en mélange)', '', 61, 2, 4, 3, 0, 'general', NOW(), NOW()),
  ('Brocoli', '', 29, 3, 3, 0, 0, 'general', NOW(), NOW()),
  ('Macédoine de légumese surgelée', '', 62, 4, 8, 1, 0, 'general', NOW(), NOW()),
  ('Poivron rouge', '', 26, 1, 5, 0, 0, 'general', NOW(), NOW()),
  ('Asperge blanche', '', 17, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Céleri-rave', '', 26, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Chou romanesco cuit', '', 35, 3, 2, 1, 0, 'general', NOW(), NOW()),
  ('Potimarron cuit à l''étouffée', '', 44, 1, 7, 1, 0, 'general', NOW(), NOW()),
  ('Asperge verte', '', 25, 3, 2, 0, 0, 'general', NOW(), NOW()),
  ('Brocoli bouilli', '', 22, 3, 1, 0, 0, 'general', NOW(), NOW()),
  ('Brocoli cuit à la vapeur', '', 38, 4, 3, 1, 0, 'general', NOW(), NOW()),
  ('Chou blanc bouilli', '', 21, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Chou de Bruxelles bouilli', '', 44, 3, 5, 0, 0, 'general', NOW(), NOW()),
  ('Chou rouge cuit à l''étouffée', '', 34, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Chou vert bouilli', '', 19, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Chou-fleur cuit à la vapeur', '', 31, 3, 3, 0, 0, 'general', NOW(), NOW()),
  ('Céleri branche cuit à l''étouffée', '', 15, 1, 2, 0, 0, 'general', NOW(), NOW()),
  ('Céleri rave bouilli', '', 26, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Fenouil cuit à l''étouffée', '', 12, 0, 2, 0, 0, 'general', NOW(), NOW()),
  ('Haricot beurre bouilli', '', 35, 2, 4, 0, 0, 'general', NOW(), NOW()),
  ('Haricot vert bouilli', '', 27, 2, 3, 0, 0, 'general', NOW(), NOW()),
  ('Navet bouilli', '', 18, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Oignon blanc', '', 39, 2, 7, 0, 0, 'general', NOW(), NOW()),
  ('Oignon nouveau', '', 28, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Oignon rouge', '', 42, 2, 8, 0, 0, 'general', NOW(), NOW()),
  ('Panais cuit à l''étouffée', '', 91, 2, 17, 1, 0, 'general', NOW(), NOW()),
  ('Poireau bouilli', '', 25, 3, 2, 0, 0, 'general', NOW(), NOW()),
  ('Poivron jaune', '', 35, 1, 5, 1, 0, 'general', NOW(), NOW()),
  ('Poivron vert', '', 27, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Potimarron bouilli', '', 39, 1, 7, 0, 0, 'general', NOW(), NOW()),
  ('Potiron rôti', '', 28, 0, 6, 0, 0, 'general', NOW(), NOW()),
  ('Salsifis bouilli', '', 57, 3, 9, 0, 0, 'general', NOW(), NOW()),
  ('Échalote sautée/poêlée sans matière grasse', '', 67, 2, 12, 0, 0, 'general', NOW(), NOW()),
  ('Épinard bouilli', '', 27, 3, 0, 1, 0, 'general', NOW(), NOW()),
  ('Chou chinois pak choï cuit', '', 13, 2, 1, 0, 0, 'general', NOW(), NOW()),
  ('Brocoli cuit', '', 30, 3, 2, 1, 0, 'general', NOW(), NOW()),
  ('Céleri branche cuit', '', 13, 1, 1, 0, 0, 'general', NOW(), NOW()),
  ('Chou rouge cuit', '', 32, 1, 5, 0, 0, 'general', NOW(), NOW()),
  ('Fenouil cuit', '', 12, 0, 2, 0, 0, 'general', NOW(), NOW()),
  ('Potimarron cuit', '', 39, 1, 7, 0, 0, 'general', NOW(), NOW()),
  ('Légumes pour couscous', '', 30, 2, 4, 0, 0, 'general', NOW(), NOW()),
  ('Légume cuit', '', 29, 2, 4, 0, 0, 'general', NOW(), NOW()),
  ('Crosne cuit', '', 49, 2, 9, 0, 0, 'general', NOW(), NOW()),
  ('Gombo cuit', '', 22, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Oignon', '', 355, 9, 74, 0, 0, 'general', NOW(), NOW()),
  ('Champignon noir', '', 0, 8, 0, 0, 0, 'general', NOW(), NOW()),
  ('Banane jaune', '', 0, 1, 0, 0, 0, 'general', NOW(), NOW()),
  ('Chips de chair de giraumon (variété locale)', '', 0, 0, 12, 0, 0, 'general', NOW(), NOW()),
  ('Chips de chair de giraumon (variété phoenix)', '', 0, 0, 14, 0, 0, 'general', NOW(), NOW()),
  ('Chou dur cuit à la vapeur', '', 0, 3, 0, 0, 0, 'general', NOW(), NOW()),
  ('Chayote appertisée', '', 0, 0, 0, 0, 0, 'general', NOW(), NOW()),
  ('Chayote surgelée', '', 0, 0, 0, 0, 0, 'general', NOW(), NOW()),
  ('Cresson cru', '', 0, 2, 0, 0, 0, 'general', NOW(), NOW()),
  ('Dachine cuit à la vapeur', '', 0, 1, 0, 0, 0, 'general', NOW(), NOW()),
  ('Farine de pulpe de patate douce', '', 223, 0, 50, 0, 0, 'general', NOW(), NOW()),
  ('Fruit à pain cuit à la vapeur', '', 0, 1, 21, 0, 0, 'general', NOW(), NOW()),
  ('Giraumon (variété locale) cuit à la vapeur', '', 0, 1, 5, 0, 0, 'general', NOW(), NOW()),
  ('Giraumon (variété locale) cru', '', 0, 0, 2, 0, 0, 'general', NOW(), NOW()),
  ('Giraumon (variété phoenix) cuit à la vapeur', '', 0, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Giraumon (variété phoenix) cru', '', 0, 0, 4, 0, 0, 'general', NOW(), NOW()),
  ('Gombo entier', '', 0, 0, 0, 0, 0, 'general', NOW(), NOW()),
  ('Gombo entier cuit à la vapeur', '', 0, 2, 5, 0, 0, 'general', NOW(), NOW()),
  ('Gombo', '', 0, 0, 5, 0, 0, 'general', NOW(), NOW()),
  ('Igname cousse-couche cuit à la vapeur', '', 89, 2, 18, 0, 0, 'general', NOW(), NOW()),
  ('Igname jaune cuit à la vapeur', '', 127, 2, 28, 0, 0, 'general', NOW(), NOW()),
  ('Igname saint martin cuit à la vapeur', '', 93, 2, 18, 0, 0, 'general', NOW(), NOW()),
  ('Topinambour cuit à la vapeur', '', 0, 1, 0, 0, 0, 'general', NOW(), NOW()),
  ('Kamanioc cuit à la vapeur', '', 0, 1, 0, 0, 0, 'general', NOW(), NOW()),
  ('Massissi cru', '', 0, 3, 0, 1, 0, 'general', NOW(), NOW()),
  ('Papaye verte', '', 0, 1, 0, 0, 0, 'general', NOW(), NOW()),
  ('Patate douce surgelée', '', 0, 0, 0, 0, 0, 'general', NOW(), NOW()),
  ('Patate douce', '', 126, 1, 25, 0, 0, 'general', NOW(), NOW()),
  ('Pois d''Angole entier cuit à la vapeur', '', 0, 16, 11, 1, 0, 'general', NOW(), NOW()),
  ('Ti nain cuit à la vapeur', '', 0, 1, 0, 0, 0, 'general', NOW(), NOW()),
  ('Fruit à pain cru', '', 0, 1, 22, 0, 0, 'general', NOW(), NOW()),
  ('Brèdes chou de Chine', '', 16, 2, 2, 0, 0, 'general', NOW(), NOW()),
  ('Tapioca cru', '', 354, 0, 88, 0, 0, 'general', NOW(), NOW()),
  ('Pomme de terre', '', 92, 2, 20, 0, 0, 'general', NOW(), NOW()),
  ('Chips de pommes de terre nature', '', 532, 6, 51, 33, 0, 'general', NOW(), NOW()),
  ('Pomme de terre nouvelle', '', 72, 1, 15, 0, 0, 'general', NOW(), NOW()),
  ('Pomme de terre appertiséee', '', 57, 2, 11, 0, 0, 'general', NOW(), NOW()),
  ('Pomme de terre noisette surgelée', '', 179, 2, 25, 7, 0, 'general', NOW(), NOW()),
  ('Pomme de terre vapeur', '', 76, 2, 16, 0, 0, 'general', NOW(), NOW()),
  ('Pomme de terre poêlée', '', 137, 3, 17, 6, 0, 'general', NOW(), NOW()),
  ('Flocons de pomme de terre', '', 376, 10, 71, 4, 0, 'general', NOW(), NOW()),
  ('Purée de pomme de terre reconstituée avec lait entier et matière grasse', '', 107, 2, 13, 5, 0, 'general', NOW(), NOW()),
  ('Purée de pomme de terre', '', 95, 2, 16, 2, 0, 'general', NOW(), NOW()),
  ('Pomme de terre dauphine surgelée', '', 242, 4, 20, 16, 0, 'general', NOW(), NOW()),
  ('Potatoes surgelées', '', 175, 3, 25, 6, 0, 'general', NOW(), NOW()),
  ('Pomme de terre sautée/poêlée/rissolée surgelée', '', 156, 3, 23, 5, 0, 'general', NOW(), NOW()),
  ('Pomme de terre de conservation', '', 73, 2, 15, 0, 0, 'general', NOW(), NOW()),
  ('Frites de pommes de terre surgelées', '', 213, 4, 33, 7, 0, 'general', NOW(), NOW()),
  ('Pomme de terre duchesse surgelée', '', 218, 3, 30, 9, 0, 'general', NOW(), NOW()),
  ('Pomme de terre sautée/poêlée/rissolée à la graisse de canard', '', 200, 2, 21, 11, 0, 'general', NOW(), NOW()),
  ('Rostis', '', 182, 2, 23, 8, 0, 'general', NOW(), NOW()),
  ('Frites de pommes de terre surgeléess', '', 142, 2, 21, 5, 0, 'general', NOW(), NOW()),
  ('Croquette de pomme de terre surgelée', '', 164, 3, 22, 7, 0, 'general', NOW(), NOW()),
  ('Poêlée de pommes de terre à la sarladaise (graisse de canard surgelée', '', 203, 2, 21, 12, 0, 'general', NOW(), NOW()),
  ('Pomme de terre grenaille surgelée', '', 133, 2, 18, 5, 0, 'general', NOW(), NOW()),
  ('Topinambour cuit', '', 69, 2, 14, 0, 0, 'general', NOW(), NOW()),
  ('Topinambour cru', '', 75, 2, 16, 0, 0, 'general', NOW(), NOW()),
  ('Taro cru', '', 105, 2, 22, 0, 0, 'general', NOW(), NOW()),
  ('Taro cuit', '', 131, 1, 30, 0, 0, 'general', NOW(), NOW()),
  ('Igname', '', 111, 2, 24, 0, 0, 'general', NOW(), NOW()),
  ('Manioc', '', 157, 1, 36, 0, 0, 'general', NOW(), NOW()),
  ('Fève à écosser', '', 62, 7, 4, 1, 0, 'general', NOW(), NOW()),
  ('Pois d''Angole vert frais cru', '', 129, 7, 19, 2, 0, 'general', NOW(), NOW()),
  ('Haricot de Lima cru', '', 105, 7, 15, 1, 0, 'general', NOW(), NOW()),
  ('Haricot flageolet frais cru', '', 153, 9, 26, 1, 0, 'general', NOW(), NOW()),
  ('Fève surgelée', '', 99, 10, 12, 0, 0, 'general', NOW(), NOW()),
  ('Lentille', '', 327, 25, 45, 2, 0, 'general', NOW(), NOW()),
  ('Haricot blanc sec', '', 307, 23, 44, 1, 0, 'general', NOW(), NOW()),
  ('Pois cassé sec', '', 347, 24, 48, 1, 0, 'general', NOW(), NOW()),
  ('Pois chiche sec', '', 350, 21, 48, 6, 0, 'general', NOW(), NOW()),
  ('Fève', '', 301, 26, 33, 2, 0, 'general', NOW(), NOW()),
  ('Haricot rouge sec', '', 314, 23, 46, 1, 0, 'general', NOW(), NOW()),
  ('Haricot mungo sec', '', 343, 25, 48, 2, 0, 'general', NOW(), NOW()),
  ('Lupin sec', '', 356, 36, 22, 10, 0, 'general', NOW(), NOW()),
  ('Lentille corail', '', 328, 28, 45, 1, 0, 'general', NOW(), NOW()),
  ('Haricot flageolet vert sec', '', 315, 19, 42, 3, 0, 'general', NOW(), NOW()),
  ('Lentille verte', '', 327, 25, 45, 2, 0, 'general', NOW(), NOW()),
  ('Lentille blonde', '', 339, 26, 48, 2, 0, 'general', NOW(), NOW()),
  ('Abricot cru', '', 44, 1, 9, 0, 0, 'general', NOW(), NOW()),
  ('Ananas cru', '', 52, 0, 12, 0, 0, 'general', NOW(), NOW()),
  ('Banane', '', 88, 1, 20, 0, 0, 'general', NOW(), NOW()),
  ('Cassis cru', '', 70, 1, 10, 0, 0, 'general', NOW(), NOW()),
  ('Ceriser', '', 54, 1, 13, 0, 0, 'general', NOW(), NOW()),
  ('Citron cru', '', 24, 0, 2, 0, 0, 'general', NOW(), NOW()),
  ('Coing cru', '', 59, 0, 13, 0, 0, 'general', NOW(), NOW()),
  ('Figue', '', 68, 1, 14, 0, 0, 'general', NOW(), NOW()),
  ('Fraise', '', 35, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Framboise', '', 48, 1, 6, 1, 0, 'general', NOW(), NOW()),
  ('Fruit de la passion cru', '', 102, 2, 11, 3, 0, 'general', NOW(), NOW()),
  ('Grenade', '', 81, 1, 14, 1, 0, 'general', NOW(), NOW()),
  ('Groseille', '', 67, 2, 7, 1, 0, 'general', NOW(), NOW()),
  ('Groseille à maquereau', '', 39, 1, 4, 1, 0, 'general', NOW(), NOW()),
  ('Kiwi cru', '', 61, 1, 11, 1, 0, 'general', NOW(), NOW()),
  ('Litchi cru', '', 78, 1, 16, 0, 0, 'general', NOW(), NOW()),
  ('Clémentine', '', 46, 1, 9, 0, 0, 'general', NOW(), NOW()),
  ('Mangue', '', 71, 1, 14, 0, 0, 'general', NOW(), NOW()),
  ('Melon cantaloup (par ex.: Charentais) cru', '', 60, 1, 15, 0, 0, 'general', NOW(), NOW()),
  ('Prune mirabelle', '', 75, 1, 18, 0, 0, 'general', NOW(), NOW()),
  ('Myrtille', '', 58, 1, 11, 0, 0, 'general', NOW(), NOW()),
  ('Mûre (de ronce)', '', 46, 1, 7, 1, 0, 'general', NOW(), NOW()),
  ('Orange', '', 42, 1, 8, 0, 0, 'general', NOW(), NOW()),
  ('Papaye', '', 40, 1, 9, 0, 0, 'general', NOW(), NOW()),
  ('Pastèque', '', 35, 1, 8, 0, 0, 'general', NOW(), NOW()),
  ('Poire', '', 57, 0, 12, 0, 0, 'general', NOW(), NOW()),
  ('Pomme', '', 54, 0, 12, 0, 0, 'general', NOW(), NOW()),
  ('Pomelo (dit Pamplemousse) cru', '', 34, 1, 6, 0, 0, 'general', NOW(), NOW()),
  ('Prune Reine-Claude', '', 69, 1, 16, 0, 0, 'general', NOW(), NOW()),
  ('Pêche', '', 38, 1, 8, 0, 0, 'general', NOW(), NOW()),
  ('Raisin blanc cru', '', 72, 1, 17, 0, 0, 'general', NOW(), NOW()),
  ('Raisin noir cru', '', 70, 1, 16, 0, 0, 'general', NOW(), NOW()),
  ('Rhubarbe', '', 18, 1, 1, 0, 0, 'general', NOW(), NOW()),
  ('Carambole', '', 28, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Cerise acérola', '', 0, 0, 7, 0, 0, 'general', NOW(), NOW()),
  ('Anone', '', 80, 2, 15, 1, 0, 'general', NOW(), NOW()),
  ('Figue de Barbarie', '', 52, 0, 10, 0, 0, 'general', NOW(), NOW()),
  ('Kaki cru', '', 66, 1, 14, 0, 0, 'general', NOW(), NOW()),
  ('Citron vert cru', '', 39, 1, 3, 0, 0, 'general', NOW(), NOW()),
  ('Goyave', '', 68, 3, 9, 1, 0, 'general', NOW(), NOW()),
  ('Pomme Canada', '', 51, 0, 12, 0, 0, 'general', NOW(), NOW()),
  ('Pomme Golden', '', 50, 0, 12, 0, 0, 'general', NOW(), NOW()),
  ('Prune', '', 52, 1, 10, 0, 0, 'general', NOW(), NOW()),
  ('Raisin Chasselas cru', '', 78, 1, 17, 1, 0, 'general', NOW(), NOW()),
  ('Pomme Granny Smith', '', 51, 0, 11, 0, 0, 'general', NOW(), NOW()),
  ('Salade de fruits', '', 79, 1, 18, 0, 0, 'general', NOW(), NOW()),
  ('Nectarine jaune', '', 50, 1, 11, 0, 0, 'general', NOW(), NOW()),
  ('Nectarine', '', 50, 1, 11, 0, 0, 'general', NOW(), NOW()),
  ('Poire Conférence', '', 49, 0, 11, 0, 0, 'general', NOW(), NOW()),
  ('Poire Williams', '', 50, 0, 12, 0, 0, 'general', NOW(), NOW()),
  ('Pomme Chantecler', '', 47, 0, 11, 0, 0, 'general', NOW(), NOW()),
  ('Pomme Gala', '', 52, 0, 12, 0, 0, 'general', NOW(), NOW()),
  ('Pomme Pink lady', '', 57, 0, 13, 0, 0, 'general', NOW(), NOW()),
  ('Pêche blanche', '', 44, 1, 9, 0, 0, 'general', NOW(), NOW()),
  ('Pêche jaune', '', 45, 1, 10, 0, 0, 'general', NOW(), NOW()),
  ('Raisin cru', '', 71, 1, 16, 0, 0, 'general', NOW(), NOW()),
  ('Nèfle du Japon', '', 48, 0, 10, 0, 0, 'general', NOW(), NOW()),
  ('Prune violette', '', 46, 1, 10, 0, 0, 'general', NOW(), NOW()),
  ('Pamplemousse chinois cru', '', 38, 1, 7, 0, 0, 'general', NOW(), NOW()),
  ('Raisin noir Muscat cru', '', 87, 1, 20, 0, 0, 'general', NOW(), NOW()),
  ('Melon miel cru', '', 22, 1, 4, 0, 0, 'general', NOW(), NOW()),
  ('Fruit cru', '', 57, 1, 12, 0, 0, 'general', NOW(), NOW()),
  ('Compote de pomme', '', 107, 0, 26, 0, 0, 'general', NOW(), NOW()),
  ('Compote de fruits rayon frais', '', 64, 0, 15, 0, 0, 'general', NOW(), NOW()),
  ('Dessert de fruits de fruits (en taux de sucres : compotes allégées en sucre...', '', 89, 0, 21, 0, 0, 'general', NOW(), NOW()),
  ('Purée de fruits de fruits "compote sans sucres ajoutés"', '', 56, 0, 13, 0, 0, 'general', NOW(), NOW()),
  ('Spécialité de fruits de fruits', '', 73, 0, 17, 0, 0, 'general', NOW(), NOW()),
  ('Spécialité de fruits de fruits (mélange chairs et/ou purées de fruits', '', 58, 0, 13, 0, 0, 'general', NOW(), NOW()),
  ('Compote de fruits sur la teneur en sucres (allégée en sucres…) ni sur le ...', '', 80, 0, 19, 0, 0, 'general', NOW(), NOW()),
  ('Purée de pommes "compote sans sucres ajoutés"', '', 56, 1, 12, 0, 0, 'general', NOW(), NOW()),
  ('Compote de fruits autres que pomme seule', '', 66, 0, 15, 0, 0, 'general', NOW(), NOW()),
  ('Compote de pêche', '', 106, 1, 25, 0, 0, 'general', NOW(), NOW()),
  ('Compote d''abricot', '', 103, 1, 24, 0, 0, 'general', NOW(), NOW()),
  ('Compote de rhubarbe', '', 111, 1, 26, 0, 0, 'general', NOW(), NOW()),
  ('Spécialité de fruits divers rayon frais', '', 79, 0, 18, 0, 0, 'general', NOW(), NOW()),
  ('Spécialité de fruits de fruits (mélange chairs et/ou purées de fruits ray...', '', 56, 0, 12, 0, 0, 'general', NOW(), NOW()),
  ('Purée de fruits de fruits "compote sans sucres ajoutés" rayon frais', '', 59, 0, 13, 0, 0, 'general', NOW(), NOW()),
  ('Compote', '', 101, 0, 24, 0, 0, 'general', NOW(), NOW()),
  ('Compote de pomme sur la teneur en sucres ni sur le rayon', '', 94, 0, 22, 0, 0, 'general', NOW(), NOW()),
  ('Purée de fruits de fruits "compote sans sucres ajoutés" sur le rayon', '', 56, 0, 13, 0, 0, 'general', NOW(), NOW()),
  ('Abricot au sirop (sans précision sur léger', '', 68, 1, 16, 0, 0, 'general', NOW(), NOW()),
  ('Macédoine appertisée', '', 65, 0, 15, 0, 0, 'general', NOW(), NOW()),
  ('Macédoine', '', 71, 0, 17, 0, 0, 'general', NOW(), NOW()),
  ('Abricot au sirop léger', '', 61, 1, 14, 0, 0, 'general', NOW(), NOW()),
  ('Abricot au sirop', '', 70, 1, 16, 0, 0, 'general', NOW(), NOW()),
  ('Ananas au jus d''ananas', '', 56, 0, 13, 0, 0, 'general', NOW(), NOW()),
  ('Ananas au sirop léger', '', 66, 0, 15, 0, 0, 'general', NOW(), NOW()),
  ('Litchi', '', 63, 1, 14, 0, 0, 'general', NOW(), NOW()),
  ('Pêche appertiséee', '', 59, 1, 14, 0, 0, 'general', NOW(), NOW()),
  ('Pêche appertisée', '', 60, 0, 14, 0, 0, 'general', NOW(), NOW()),
  ('Poire au sirop léger appertiséee', '', 64, 0, 14, 0, 0, 'general', NOW(), NOW()),
  ('Poire au sirop léger appertisée', '', 63, 0, 15, 0, 0, 'general', NOW(), NOW()),
  ('Amande', '', 615, 23, 10, 51, 0, 'general', NOW(), NOW()),
  ('Cacahuète', '', 623, 26, 15, 49, 0, 'general', NOW(), NOW()),
  ('Cacahuète grillée', '', 635, 26, 14, 51, 0, 'general', NOW(), NOW()),
  ('Noisette', '', 632, 17, 7, 57, 0, 'general', NOW(), NOW()),
  ('Noix', '', 709, 16, 7, 67, 0, 'general', NOW(), NOW()),
  ('Noix de coco', '', 369, 4, 5, 35, 0, 'general', NOW(), NOW()),
  ('Noix du Brésil', '', 701, 16, 4, 67, 0, 'general', NOW(), NOW()),
  ('Pistache grillée', '', 617, 22, 16, 50, 0, 'general', NOW(), NOW()),
  ('Sésame', '', 606, 21, 13, 50, 0, 'general', NOW(), NOW()),
  ('Tournesol', '', 653, 25, 10, 56, 0, 'general', NOW(), NOW()),
  ('Purée de marrons appertisée', '', 102, 3, 23, 0, 0, 'general', NOW(), NOW()),
  ('Mélange apéritif de graines salées et fruits séchés', '', 583, 20, 24, 44, 0, 'general', NOW(), NOW()),
  ('Mélange apéritif de graines salées et raisins secs', '', 561, 20, 27, 40, 0, 'general', NOW(), NOW()),
  ('Noix de cajou grillée', '', 632, 18, 27, 50, 0, 'general', NOW(), NOW()),
  ('Châtaigne', '', 123, 2, 23, 1, 0, 'general', NOW(), NOW()),
  ('Châtaigne grillée', '', 211, 4, 41, 2, 0, 'general', NOW(), NOW()),
  ('Pignon de pin', '', 712, 16, 3, 68, 0, 'general', NOW(), NOW()),
  ('Noix de pécan', '', 727, 11, 4, 72, 0, 'general', NOW(), NOW()),
  ('Noix de macadamia', '', 757, 9, 5, 76, 0, 'general', NOW(), NOW()),
  ('Luzerne', '', 426, 35, 39, 13, 0, 'general', NOW(), NOW()),
  ('Noisette grillée', '', 684, 17, 9, 62, 0, 'general', NOW(), NOW()),
  ('Lin', '', 528, 22, 6, 40, 0, 'general', NOW(), NOW()),
  ('Cacahuète grillée à sec', '', 615, 25, 18, 48, 0, 'general', NOW(), NOW()),
  ('Amande grillée', '', 647, 24, 12, 54, 0, 'general', NOW(), NOW()),
  ('Noix de macadamia grillée', '', 724, 8, 10, 70, 0, 'general', NOW(), NOW()),
  ('Chia', '', 454, 20, 8, 31, 0, 'general', NOW(), NOW()),
  ('Mélange apéritif de graines et fruits séchés', '', 493, 10, 51, 26, 0, 'general', NOW(), NOW()),
  ('Mélange apéritif de graines et raisins secs', '', 541, 15, 32, 37, 0, 'general', NOW(), NOW()),
  ('Noix de cajou grillée à sec', '', 630, 21, 24, 49, 0, 'general', NOW(), NOW()),
  ('Mélange apéritif de graines grillées', '', 637, 21, 10, 55, 0, 'general', NOW(), NOW()),
  ('Chanvre', '', 617, 37, 5, 49, 0, 'general', NOW(), NOW()),
  ('Fruits à coques et cacahuète', '', 630, 24, 18, 50, 0, 'general', NOW(), NOW()),
  ('Beurre de cacahuète', '', 643, 25, 17, 51, 0, 'general', NOW(), NOW()),
  ('Tahin', '', 631, 20, 14, 53, 0, 'general', NOW(), NOW()),
  ('Soja', '', 441, 40, 21, 20, 0, 'general', NOW(), NOW()),
  ('Épeautre cru', '', 344, 16, 60, 2, 0, 'general', NOW(), NOW()),
  ('Blé de Khorasan cru', '', 342, 16, 60, 2, 0, 'general', NOW(), NOW()),
  ('Blé dur complet cru', '', 342, 15, 59, 2, 0, 'general', NOW(), NOW()),
  ('Blé dur complet', '', 359, 15, 68, 2, 0, 'general', NOW(), NOW()),
  ('Riz blanc cru', '', 350, 7, 78, 1, 0, 'general', NOW(), NOW()),
  ('Riz blanc étuvé cru', '', 361, 8, 79, 1, 0, 'general', NOW(), NOW()),
  ('Riz complet cru', '', 350, 7, 71, 3, 0, 'general', NOW(), NOW()),
  ('Riz sauvage cru', '', 344, 12, 69, 1, 0, 'general', NOW(), NOW()),
  ('Riz rouge cru', '', 352, 8, 71, 3, 0, 'general', NOW(), NOW()),
  ('Riz thaï cru', '', 351, 7, 78, 1, 0, 'general', NOW(), NOW()),
  ('Riz mélange de variétés (blanc complet rouge cru', '', 355, 8, 78, 1, 0, 'general', NOW(), NOW()),
  ('Avoine', '', 378, 18, 56, 7, 0, 'general', NOW(), NOW()),
  ('Orge complète', '', 334, 13, 56, 2, 0, 'general', NOW(), NOW()),
  ('Orge perlée', '', 346, 11, 69, 1, 0, 'general', NOW(), NOW()),
  ('Mil complet cru', '', 360, 12, 64, 4, 0, 'general', NOW(), NOW()),
  ('Quinoa cru', '', 358, 14, 58, 6, 0, 'general', NOW(), NOW()),
  ('Amarante', '', 369, 15, 59, 7, 0, 'general', NOW(), NOW()),
  ('Sorgho complet cru', '', 349, 11, 65, 3, 0, 'general', NOW(), NOW()),
  ('Sarrasin complet cru', '', 362, 13, 68, 3, 0, 'general', NOW(), NOW()),
  ('Seigle complet cru', '', 332, 11, 61, 2, 0, 'general', NOW(), NOW()),
  ('Semoule de blé dur', '', 350, 13, 70, 1, 0, 'general', NOW(), NOW()),
  ('Mélange de céréales et légumes secs cru', '', 354, 15, 59, 4, 0, 'general', NOW(), NOW()),
  ('Polentae', '', 350, 8, 74, 2, 0, 'general', NOW(), NOW()),
  ('Graine de couscous (semoule de blé dur précuite)', '', 366, 14, 73, 1, 0, 'general', NOW(), NOW()),
  ('Boulgour de blé cru', '', 347, 13, 66, 1, 0, 'general', NOW(), NOW()),
  ('Pâtes sèches', '', 364, 13, 73, 2, 0, 'general', NOW(), NOW()),
  ('Pâtes fraîches', '', 283, 11, 54, 2, 0, 'general', NOW(), NOW()),
  ('Pâtes', '', 371, 13, 71, 3, 0, 'general', NOW(), NOW()),
  ('Pâtes sèches au blé complet', '', 353, 13, 68, 2, 0, 'general', NOW(), NOW()),
  ('Vermicelles de riz sèches', '', 365, 8, 81, 1, 0, 'general', NOW(), NOW()),
  ('Vermicelles de soja sèches', '', 343, 0, 85, 0, 0, 'general', NOW(), NOW()),
  ('Gnocchi à la pomme de terre', '', 176, 5, 35, 1, 0, 'general', NOW(), NOW()),
  ('Gnocchi à la semoule', '', 200, 6, 37, 3, 0, 'general', NOW(), NOW()),
  ('Frik (blé dur immature concassé) cru', '', 323, 10, 56, 2, 0, 'general', NOW(), NOW()),
  ('Gari', '', 340, 1, 82, 1, 0, 'general', NOW(), NOW()),
  ('Pain', '', 276, 9, 55, 1, 0, 'general', NOW(), NOW()),
  ('Pain blanc (par ex. : baguette', '', 287, 9, 58, 1, 0, 'general', NOW(), NOW()),
  ('Pain au levain', '', 261, 8, 53, 1, 0, 'general', NOW(), NOW()),
  ('Pain de tradition française (par ex. : baguette', '', 279, 9, 57, 1, 0, 'general', NOW(), NOW()),
  ('Pain blanc précuit', '', 265, 8, 54, 1, 0, 'general', NOW(), NOW()),
  ('Pain bis (à la farine T80 ou T110)', '', 265, 9, 54, 0, 0, 'general', NOW(), NOW()),
  ('Pain sans gluten précuit', '', 234, 3, 40, 5, 0, 'general', NOW(), NOW()),
  ('Pain aux céréales et/ou aux graines', '', 282, 9, 40, 8, 0, 'general', NOW(), NOW()),
  ('Pain de campagne', '', 257, 7, 49, 3, 0, 'general', NOW(), NOW()),
  ('Pain complet au seigle', '', 213, 6, 40, 1, 0, 'general', NOW(), NOW()),
  ('Pain aux graines sans gluten', '', 266, 5, 39, 9, 0, 'general', NOW(), NOW()),
  ('Pain de mie complet', '', 245, 8, 43, 3, 0, 'general', NOW(), NOW()),
  ('Pain complet', '', 234, 10, 41, 2, 0, 'general', NOW(), NOW()),
  ('Pain de mie aux céréales et/ou graines', '', 290, 10, 44, 7, 0, 'general', NOW(), NOW()),
  ('Pain azyme', '', 372, 12, 75, 2, 0, 'general', NOW(), NOW()),
  ('Pain au son', '', 244, 9, 44, 2, 0, 'general', NOW(), NOW()),
  ('Pain de mie blanc sans gluten', '', 242, 4, 41, 5, 0, 'general', NOW(), NOW()),
  ('Pain de mie blanc', '', 290, 8, 48, 6, 0, 'general', NOW(), NOW()),
  ('Pain de seigle et froment', '', 260, 9, 52, 1, 0, 'general', NOW(), NOW()),
  ('Pain sans gluten', '', 249, 5, 37, 7, 0, 'general', NOW(), NOW()),
  ('Pain blanc', '', 282, 10, 57, 1, 0, 'general', NOW(), NOW()),
  ('Pain panini', '', 254, 8, 51, 1, 0, 'general', NOW(), NOW()),
  ('Pain pita', '', 249, 8, 49, 2, 0, 'general', NOW(), NOW()),
  ('Pain de mie brioché', '', 312, 9, 51, 7, 0, 'general', NOW(), NOW()),
  ('Pain aux céréales et/ou graines', '', 269, 11, 47, 3, 0, 'general', NOW(), NOW()),
  ('Muffin anglais complet', '', 205, 12, 31, 2, 0, 'general', NOW(), NOW()),
  ('Muffin anglais', '', 228, 10, 43, 1, 0, 'general', NOW(), NOW()),
  ('Pain bagel', '', 301, 11, 53, 5, 0, 'general', NOW(), NOW()),
  ('Pain pour burger', '', 283, 9, 47, 5, 0, 'general', NOW(), NOW()),
  ('Bretzel pain frais', '', 330, 10, 55, 7, 0, 'general', NOW(), NOW()),
  ('Tortilla souple (à garnir)', '', 316, 7, 58, 6, 0, 'general', NOW(), NOW()),
  ('Blinis', '', 270, 6, 35, 12, 0, 'general', NOW(), NOW()),
  ('Biscotte classique', '', 394, 11, 73, 5, 0, 'general', NOW(), NOW()),
  ('Biscotte briochée', '', 440, 9, 72, 11, 0, 'general', NOW(), NOW()),
  ('Biscotte au germe de blé', '', 386, 11, 70, 5, 0, 'general', NOW(), NOW()),
  ('Biscotte', '', 402, 12, 75, 5, 0, 'general', NOW(), NOW()),
  ('Biscotte aux céréales', '', 404, 13, 68, 7, 0, 'general', NOW(), NOW()),
  ('Biscotte au blé complet', '', 389, 12, 66, 6, 0, 'general', NOW(), NOW()),
  ('Cracker de table aux graines', '', 445, 16, 50, 18, 0, 'general', NOW(), NOW()),
  ('Cracker de table au fromage et aux graines', '', 455, 20, 47, 19, 0, 'general', NOW(), NOW()),
  ('Cracker de table au blé complet', '', 436, 14, 56, 15, 0, 'general', NOW(), NOW()),
  ('Cracker de table au froment', '', 442, 11, 69, 12, 0, 'general', NOW(), NOW()),
  ('Galette de riz complet soufflé', '', 381, 9, 78, 3, 0, 'general', NOW(), NOW()),
  ('Galette de céréales soufflées', '', 388, 11, 78, 3, 0, 'general', NOW(), NOW()),
  ('Galette de maïs soufflé', '', 387, 7, 84, 2, 0, 'general', NOW(), NOW()),
  ('Galette de céréale(s) soufflée(s)', '', 382, 9, 78, 4, 0, 'general', NOW(), NOW()),
  ('Tartine croustillante au seigle', '', 342, 10, 57, 3, 0, 'general', NOW(), NOW()),
  ('Toast', '', 405, 12, 74, 6, 0, 'general', NOW(), NOW()),
  ('Pain grillé au froment', '', 399, 11, 72, 6, 0, 'general', NOW(), NOW()),
  ('Pain grillé au blé complet', '', 390, 11, 69, 6, 0, 'general', NOW(), NOW()),
  ('Pain grillé brioché', '', 427, 11, 68, 11, 0, 'general', NOW(), NOW()),
  ('Petit pain grillé suédois au froment', '', 411, 10, 72, 8, 0, 'general', NOW(), NOW()),
  ('Petit pain grillé suédois aux céréales et graines', '', 404, 11, 69, 8, 0, 'general', NOW(), NOW()),
  ('Tartine craquante extrudée', '', 385, 10, 76, 4, 0, 'general', NOW(), NOW()),
  ('Tartine craquante extrudées', '', 376, 11, 71, 4, 0, 'general', NOW(), NOW()),
  ('Petit pain grillé suédois au blé complet', '', 391, 12, 65, 7, 0, 'general', NOW(), NOW()),
  ('Petit pain grillé suédois aux fruits', '', 386, 10, 74, 5, 0, 'general', NOW(), NOW()),
  ('Petit pain grillé suédois brioché', '', 421, 10, 69, 11, 0, 'general', NOW(), NOW()),
  ('Pain grillé aux céréales', '', 417, 14, 70, 7, 0, 'general', NOW(), NOW()),
  ('Croûton', '', 374, 14, 70, 3, 0, 'general', NOW(), NOW()),
  ('Croûton nature', '', 459, 10, 62, 18, 0, 'general', NOW(), NOW()),
  ('Chapelure', '', 365, 10, 74, 2, 0, 'general', NOW(), NOW()),
  ('Gressin', '', 428, 13, 69, 11, 0, 'general', NOW(), NOW()),
  ('Mélange de fromages râpés (ex : spécial gratins', '', 386, 31, 0, 29, 0, 'general', NOW(), NOW()),
  ('Fromage', '', 324, 21, 1, 26, 0, 'general', NOW(), NOW()),
  ('Spécialité fromagère non affinée en coque', '', 242, 5, 4, 23, 0, 'general', NOW(), NOW()),
  ('Fromage type feta', '', 273, 15, 1, 23, 0, 'general', NOW(), NOW()),
  ('Bouchée apéritive de fromage au lait de vache non affiné', '', 274, 11, 3, 24, 0, 'general', NOW(), NOW()),
  ('Feta', '', 284, 15, 0, 24, 0, 'general', NOW(), NOW()),
  ('Fromage frais', '', 225, 6, 3, 21, 0, 'general', NOW(), NOW()),
  ('Brousse (fromage de brebis frais au lactosérum)', '', 142, 9, 5, 9, 0, 'general', NOW(), NOW()),
  ('Burrata', '', 259, 11, 1, 23, 0, 'general', NOW(), NOW()),
  ('Fromage à effilocher', '', 307, 23, 3, 22, 0, 'general', NOW(), NOW()),
  ('Fromage de chèvre frais palet', '', 194, 12, 3, 15, 0, 'general', NOW(), NOW()),
  ('Fromage de chèvre à tartiner', '', 161, 11, 2, 12, 0, 'general', NOW(), NOW()),
  ('Fromage de lactosérum de brebis', '', 190, 10, 4, 15, 0, 'general', NOW(), NOW()),
  ('Mascarpone', '', 369, 6, 3, 37, 0, 'general', NOW(), NOW()),
  ('Mozzarella au lait de vache', '', 227, 16, 1, 18, 0, 'general', NOW(), NOW()),
  ('Mozzarella au lait de bufflonne', '', 260, 14, 0, 22, 0, 'general', NOW(), NOW());
